version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/user_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - JWT_EXPIRE=24h
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5001,http://localhost:5002,http://localhost:5003,http://localhost:5004,http://localhost:5005,http://localhost:5006,http://localhost:5007
    networks:
      - ticket-network
    restart: unless-stopped

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/booking_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - USER_SERVICE_URL=http://user-service:5001
      - EVENT_SERVICE_URL=http://event-service:5002
      - PAYMENT_SERVICE_URL=http://payment-service:5003
      - NOTIFICATION_SERVICE_URL=http://notification-service:5006
      - ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - user-service
    networks:
      - ticket-network
    restart: unless-stopped

  event-service:
    build: ./event-service
    container_name: event-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/event_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - USER_SERVICE_URL=http://user-service:5001
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - ticket-network
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/payment_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - BOOKING_SERVICE_URL=http://booking-service:5004
      - NOTIFICATION_SERVICE_URL=http://notification-service:5006
      - STRIPE_SECRET_KEY=sk_test_51TDgVrFvYwhhWZpYYy9cw75I9i4KWC8z2qyfy0lzXGqOHSfgDCaKAJmORSy7DedhbsMnbosXC1DCKaWSQLUNrXkL006Vl2jwfk
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - ticket-network
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "5006:5006"
    environment:
      - PORT=5006
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/notification_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - ticket-network
    restart: unless-stopped

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/review_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - USER_SERVICE_URL=http://user-service:5001
      - EVENT_SERVICE_URL=http://event-service:5002
      - BOOKING_SERVICE_URL=http://booking-service:5004
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - ticket-network
    restart: unless-stopped

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - "5007:5007"
    environment:
      - PORT=5007
      - MONGO_URI=mongodb+srv://ctse:ctse123@cluster0.afkbz0b.mongodb.net/reporting_db?appName=Cluster0
      - JWT_SECRET=ctse-super-secret-jwt-key-2026
      - NODE_ENV=development
      - SERVICE_KEY=ctse-internal-service-key-2026
      - USER_SERVICE_URL=http://user-service:5001
      - EVENT_SERVICE_URL=http://event-service:5002
      - BOOKING_SERVICE_URL=http://booking-service:5004
      - PAYMENT_SERVICE_URL=http://payment-service:5003
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - ticket-network
    restart: unless-stopped

networks:
  ticket-network:
    driver: bridge
