sonar.projectKey=ctse-ticket_event-service
sonar.organization=ctse-ticket
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,tests/**
