sonar.projectKey=event-booking-reporting-service
sonar.organization=ctse-ticket
sonar.projectName=Reporting Service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
